on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ðŸ“‚ Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
          port: 21
          server-dir: ${{ secrets.STAGING_FTP_PATH }}
          protocol: ftp
          exclude: |
            public/**
            **/public/**

      - name: ðŸš€ Run Laravel commands on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_USER_STAGING }}
          key: ${{ secrets.DEPLOY_SERVER_KEY_STAGING }}
          port: 3117
          script: |
            cd ${{ secrets.SSH_DIR_STAGING }}
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan optimize:clear
