on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}

      - name: âœ… SSH into Server & Deploy Laravel
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.SSH_USER_STAGING }}
          key: ${{ secrets.DEPLOY_SERVER_KEY_STAGING }}
          port: 21
          script: |
            cd ${{ secrets.SSH_DIR_STAGING }}
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan optimize:clear